[[questions]]
alternatives = ["1771", "1871", "1881"]
answers = ["1781"]
question = "When was the first known use of the word 'quiz'"

[[questions]]
alternatives = ["get", "print", "write"]
answers = ["input"]
question = "Which built-in function can get information from the user"

[[questions]]
alternatives = [
  "To combine several strings into one",
  "To compress several files into one archive",
  "To get information from the user",
]
answers = ["To iterate over two or more sequences at the same time"]
question = "What's the purpose of the built-in zip() function"

[[questions]]
alternatives = ["key", "True", "False"]
answers = ["None"]
question = "What does dict.get(key) return if key isn't found in dict"

[[questions]]
alternatives = [
  "enumerate(iterable, start=1)",
  "range(iterable)",
  "range(iterable, start=1)",
]
answers = ["enumerate(iterable)"]
question = "How do you iterate over both indices and elements in an iterable"

[[questions]]
alternatives = ["Named expression", "Walrus operator", "Colon equals operator"]
answers = ["Assignment expression"]
question = "What's the official name of the := operator"

[[questions]]
alternatives = [
  "The random numbers are more random.",
  "The computer clock is reset.",
  "The first random number is always 42.",
]
answers = ["The random numbers are reproducible."]
question = "What's one effect of calling random.seed(42)"

[[questions]]
alternatives = [
  "When the file is imported as a module",
  "When the file has a valid name",
  "When the file only has one function",
]
answers = ["When the file is run as a script"]
question = "When does __name__ == '__main__' equal True in a Python file"

[[questions]]
alternatives = ["3.9", "3.10", "3.12"]
answers = ["3.11"]
question = "Which version of Python is the first with TOML support built in"

[[questions]]
alternatives = ["List", "Sequence", "Set"]
answers = ["Array"]
question = "What's the name of the list-like data structure in TOML"

[[questions]]
alternatives = ["python quiz", "python -m quiz.py"]
answers = ["python quiz.py", "python -m quiz"]
question = "How can you run a Python script named quiz.py"
