[[questions]]
alternatives = ["1771", "1871", "1881"]
answers = ["1781"]
question = "When was the first known use of the word 'quiz'"

[[questions]]
alternatives = ["get", "print", "write"]
answers = ["input"]
question = "Which built-in function can get information from the user"

[[questions]]
alternatives = [
  "To combine several strings into one",
  "To compress several files into one archive",
  "To get information from the user",
]
answers = ["To iterate over two or more sequences at the same time"]
question = "What's the purpose of the built-in zip() function"

[[questions]]
alternatives = ["key", "True", "False"]
answers = ["None"]
question = "What does dict.get(key) return if key isn't found in dict"

[[questions]]
alternatives = [
  "enumerate(iterable, start=1)",
  "range(iterable)",
  "range(iterable, start=1)",
]
answers = ["enumerate(iterable)"]
question = "How do you iterate over both indices and elements in an iterable"

[[questions]]
alternatives = ["Named expression", "Walrus operator", "Colon equals operator"]
answers = ["Assignment expression"]
question = "What's the official name of the := operator"

[[questions]]
alternatives = [
  "The random numbers are more random.",
  "The computer clock is reset.",
  "The first random number is always 42.",
]
answers = ["The random numbers are reproducible."]
question = "What's one effect of calling random.seed(42)"

[[questions]]
alternatives = [
  "When the file is imported as a module",
  "When the file has a valid name",
  "When the file only has one function",
]
answers = ["When the file is run as a script"]
question = "When does __name__ == '__main__' equal True in a Python file"

[[questions]]
alternatives = ["3.9", "3.10", "3.12"]
answers = ["3.11"]
question = "Which version of Python is the first with TOML support built in"

[[questions]]
alternatives = ["List", "Sequence", "Set"]
answers = ["Array"]
question = "What's the name of the list-like data structure in TOML"

[[questions]]
alternatives = ["python quiz", "python -m quiz.py"]
answers = ["python quiz.py", "python -m quiz"]
hint = "One option uses the filename, and the other uses the module name."
question = "How can you run a Python script named quiz.py"

[[questions]]
alternatives = [
  "A Pretty Exciting Policy",
  "A Preciously Evolved Python",
  "A Potentially Epic Prize",
]
answers = ["A Python Enhancement Proposal"]
explanation = """
    Python Enhancement Proposals (PEPs) are design documents that provide
    information to the Python community. PEPs are used to propose new features
    for the Python language, to collect community input on an issue, and to
    document design decisions made about the language.
"""
hint = "PEPs are used to evolve Python."
question = "What's a PEP"

[[questions]]
alternatives = [
  "By using the built-in @docstring decorator",
  "By returning a string from the function",
]
answers = [
  "By writing a string literal as the first statement in the function",
  "By assigning a string to the function's .__doc__ attribute",
]
explanation = """
    Docstrings document functions and other Python objects. A docstring is a
    string literal that occurs as the first statement in a module, function,
    class, or method definition. Such a docstring becomes the .__doc__ special
    attribute of that object. See PEP 257 for more information.

    There is no built-in @docstring decorator. Many functions naturally return
    strings. Such a feature can therefore not be used for docstrings.
"""
hint = "They're parsed from your code and stored on the function object."
question = "How can you add a docstring to a function"
